{% set packages = ["systemd", "rsyslog"] + (extra_packages or []) %}

FROM rockylinux:9

ENV container docker
STOPSIGNAL SIGRTMIN+3

RUN dnf -y install {{ packages | join(" ") }} && \
    dnf clean all && \
    rm -rf /var/cache/dnf

VOLUME ["/sys/fs/cgroup"]
CMD ["/sbin/init"]
